# Generated by Django 2.2.7 on 2019-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0002_auto_20191021_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='author',
            field=models.CharField(default='', max_length=255, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='dev_status',
            field=models.TextField(default='', verbose_name='Development Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='raw_rule',
            field=models.TextField(default='', verbose_name='Raw rule (JSON)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='references',
            field=models.ManyToManyField(blank=True, to='atc.References', verbose_name='References(s)'),
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='severity',
            field=models.TextField(default='', verbose_name='Severity Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='tag',
            field=models.ManyToManyField(blank=True, to='atc.Tag'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='fields',
            field=models.ManyToManyField(related_name='fields', to='atc.LogField', verbose_name='Log Field(s)'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='loggingpolicy',
            field=models.ManyToManyField(blank=True, related_name='loggin_policy', to='atc.LoggingPolicy', verbose_name='Logging Policy(ies)'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='references',
            field=models.ManyToManyField(blank=True, to='atc.References', verbose_name='References(s)'),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='data_needed',
            field=models.ManyToManyField(blank=True, to='atc.DataNeeded'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='data_needed',
            field=models.ManyToManyField(related_name='data_needed', to='atc.DataNeeded', verbose_name='Data Needed'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='data_to_enrich',
            field=models.ManyToManyField(blank=True, related_name='data_to_enrich', to='atc.DataNeeded', verbose_name='Data to Enrich'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='new_fields',
            field=models.ManyToManyField(blank=True, related_name='new_field', to='atc.LogField', verbose_name='New field(s)'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='references',
            field=models.ManyToManyField(blank=True, to='atc.References', verbose_name='References(s)'),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='_enrichment_requirements_+', to='atc.Enrichment', verbose_name='Requirement(s)'),
        ),
        migrations.AlterField(
            model_name='loggingpolicy',
            name='eventID',
            field=models.ManyToManyField(to='atc.EventID', verbose_name='Event ID(s)'),
        ),
        migrations.AlterField(
            model_name='loggingpolicy',
            name='references',
            field=models.ManyToManyField(blank=True, to='atc.References', verbose_name='References(s)'),
        ),
    ]
