# Generated by Django 2.2.7 on 2020-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0006_dataneeded_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseaction',
            name='linked_ra',
        ),
        migrations.AddField(
            model_name='responseaction',
            name='linked_ra',
            field=models.ManyToManyField(blank=True, null=True, related_name='_responseaction_linked_ra_+', to='atc.ResponseAction', verbose_name='Linked Response Action(s)'),
        ),
        migrations.RemoveField(
            model_name='responseaction',
            name='references',
        ),
        migrations.AddField(
            model_name='responseaction',
            name='references',
            field=models.ManyToManyField(blank=True, null=True, related_name='references', to='atc.References', verbose_name='References(s)'),
        ),
    ]
