# Generated by Django 2.2.7 on 2020-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0007_auto_20200407_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseaction',
            name='linked_ra',
            field=models.ManyToManyField(blank=True, related_name='_responseaction_linked_ra_+', to='atc.ResponseAction', verbose_name='Linked Response Action(s)'),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='references', to='atc.References', verbose_name='References(s)'),
        ),
    ]
