# Generated by Django 2.2.7 on 2020-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0010_auto_20200412_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseplaybook',
            name='tags',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='atc.Tag', verbose_name='Tag(s)'),
        ),
    ]
