# Generated by Django 2.2.7 on 2020-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0011_auto_20200412_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseplaybook',
            name='tags',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='atc.Tag', verbose_name='Tag(s)'),
        ),
    ]
