# Generated by Django 2.2.7 on 2020-04-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0015_auto_20200412_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionrule',
            old_name='tag',
            new_name='tags',
        ),
    ]
