# Generated by Django 2.2.7 on 2020-04-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0016_auto_20200412_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseplaybook',
            name='pap',
            field=models.CharField(choices=[('WHITE', 'White'), ('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red')], max_length=5, verbose_name='PAP'),
        ),
        migrations.AlterField(
            model_name='responseplaybook',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=6, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='responseplaybook',
            name='tlp',
            field=models.CharField(choices=[('WHITE', 'White'), ('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red')], max_length=5, verbose_name='TLP'),
        ),
    ]
