# Generated by Django 2.2.6 on 2019-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichment',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='requirement',
        ),
        migrations.AddField(
            model_name='enrichment',
            name='new_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_field', to='atc.LogField', verbose_name='New field(s)'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='_enrichment_requirements_+', to='atc.Enrichment', verbose_name='Requirement(s)'),
        ),
    ]
