# Generated by Django 2.2.4 on 2019-09-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0002_auto_20190901_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataneeded',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='atc.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to='atc.Channel', verbose_name='Channel'),
        ),
        migrations.RemoveField(
            model_name='dataneeded',
            name='log_field',
        ),
        migrations.AddField(
            model_name='dataneeded',
            name='log_field',
            field=models.ManyToManyField(null=True, related_name='log_field', to='atc.LogField', verbose_name='Log Field(s)'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='log_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_type', to='atc.LogType', verbose_name='Log Type'),
        ),
        migrations.RemoveField(
            model_name='dataneeded',
            name='logging_policy',
        ),
        migrations.AddField(
            model_name='dataneeded',
            name='logging_policy',
            field=models.ManyToManyField(blank=True, null=True, related_name='loggin_policy', to='atc.LoggingPolicy', verbose_name='Logging Policy(ies)'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform', to='atc.Platform', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='dataneeded',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='atc.Provider', verbose_name='Provider'),
        ),
        migrations.RemoveField(
            model_name='dataneeded',
            name='reference',
        ),
        migrations.AddField(
            model_name='dataneeded',
            name='reference',
            field=models.ManyToManyField(blank=True, null=True, to='atc.Reference', verbose_name='Reference(s)'),
        ),
    ]
