# Generated by Django 2.2.7 on 2019-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0003_auto_20191110_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='raw_rule',
            field=models.TextField(verbose_name='Raw rule (JSON as a string)'),
        ),
    ]
