# Generated by Django 2.2.4 on 2019-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0003_auto_20190901_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='data_needed',
            field=models.ManyToManyField(blank=True, null=True, to='atc.DataNeeded'),
        ),
    ]
