# Generated by Django 2.2.7 on 2020-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0008_auto_20200412_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseplaybook',
            name='linked_rp',
            field=models.ManyToManyField(blank=True, related_name='_responseplaybook_linked_rp_+', to='atc.ResponsePlaybook', verbose_name='Linked Response Playbook(s)'),
        ),
    ]
