# Generated by Django 2.2.7 on 2020-04-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0009_responseplaybook_linked_rp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responseplaybook',
            old_name='tag',
            new_name='tags',
        ),
    ]
