# Generated by Django 2.2.7 on 2020-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0014_auto_20200412_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseplaybook',
            name='containment',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='containment',
            field=models.ManyToManyField(related_name='containment', to='atc.ResponseAction', verbose_name='Containment'),
        ),
        migrations.RemoveField(
            model_name='responseplaybook',
            name='eradication',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='eradication',
            field=models.ManyToManyField(related_name='eradication', to='atc.ResponseAction', verbose_name='Eradication'),
        ),
        migrations.RemoveField(
            model_name='responseplaybook',
            name='identification',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='identification',
            field=models.ManyToManyField(related_name='identification', to='atc.ResponseAction', verbose_name='Identification'),
        ),
        migrations.RemoveField(
            model_name='responseplaybook',
            name='lessons_learned',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='lessons_learned',
            field=models.ManyToManyField(related_name='lessons_learned', to='atc.ResponseAction', verbose_name='Lessons learned'),
        ),
        migrations.RemoveField(
            model_name='responseplaybook',
            name='recovery',
        ),
        migrations.AddField(
            model_name='responseplaybook',
            name='recovery',
            field=models.ManyToManyField(related_name='recovery', to='atc.ResponseAction', verbose_name='Recovery'),
        ),
    ]
